name: Blind Test

on: push

jobs:
  default:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8]
        include:
          - os: ubuntu-latest
            python-version: 3.9

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install bandit flake8 pylint
        pip install -r requirements.txt
        python setup.py install
    - name: Lint
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8' }}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 minode --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 minode --count --statistics
        pylint minode --exit-zero --rcfile=tox.ini
        bandit -r --exit-zero -x tests minode
    - name: Test
      run: |
        export PYTHONWARNINGS=all
        coverage run -a -m tests
    - name: Summary
      run: coverage report
