name: Testing
on: [push]

jobs:
  default:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -yq --no-install-suggests --no-install-recommends \
          python3-dev python3-pip python3-venv python-is-python3
          pip install setuptools wheel
          pip install --upgrade pip tox virtualenv
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Quick lint
        run: tox -e lint-basic
      - name: Run tests
        run: tox
